// Aircraft catalogue — hand-curated seed of ~150 of the most-listed
// makes & models in the Australian and US markets, with verified specs.
//
// This file ships in the JS bundle so the make/model picker on /sell, the
// hero search, and the buy-page filter rail all work on day one even if
// the Supabase aircraft_models table is empty. The runtime hook merges
// this seed with whatever's in the DB so admin / FAA-import / CASA-import
// additions appear automatically.
//
// Spec fields are LEFT NULL where the value is genuinely uncertain — a
// missing field is never wrong, but a wrong field damages trust. Cruise
// speeds are typical book values at 75% power at optimum altitude; range
// is no-reserve still-air; fuel burn is litres per hour at cruise.
//
// Provenance: type designators per ICAO Doc 8643. MTOW / seats / engines
// per manufacturer type certificate data sheets. Mission tags are
// editorial — debate-friendly but defensible.

export const MAKES_SEED = [
  { slug: 'airbus-helicopters', name: 'Airbus Helicopters', country: 'France', founded_year: 1992, homepage_url: 'https://www.airbus.com/en/products-services/helicopters' },
  { slug: 'aviat',              name: 'Aviat Aircraft',     country: 'USA',    founded_year: 1995, homepage_url: 'https://aviataircraft.com/' },
  { slug: 'beechcraft',         name: 'Beechcraft',         country: 'USA',    founded_year: 1932, homepage_url: 'https://txtav.com/en/beechcraft' },
  { slug: 'bell',               name: 'Bell',               country: 'USA',    founded_year: 1935, homepage_url: 'https://www.bellflight.com/' },
  { slug: 'bristell',           name: 'Bristell',           country: 'Czechia', founded_year: 2010 },
  { slug: 'cessna',             name: 'Cessna',             country: 'USA',    founded_year: 1927, homepage_url: 'https://cessna.txtav.com/' },
  { slug: 'cirrus',             name: 'Cirrus',             country: 'USA',    founded_year: 1984, homepage_url: 'https://cirrusaircraft.com/' },
  { slug: 'cubcrafters',        name: 'CubCrafters',        country: 'USA',    founded_year: 1980 },
  { slug: 'daher',              name: 'Daher',              country: 'France', founded_year: 1863, homepage_url: 'https://www.tbm.aero/' },
  { slug: 'diamond',            name: 'Diamond Aircraft',   country: 'Austria', founded_year: 1981, homepage_url: 'https://www.diamondaircraft.com/' },
  { slug: 'embraer',            name: 'Embraer',            country: 'Brazil', founded_year: 1969 },
  { slug: 'extra',              name: 'Extra Aircraft',     country: 'Germany', founded_year: 1980 },
  { slug: 'foxbat',             name: 'Aeroprakt (Foxbat)', country: 'Ukraine', founded_year: 1989 },
  { slug: 'gippsaero',          name: 'GippsAero',          country: 'Australia', founded_year: 1990, homepage_url: 'https://gippsaero.com/' },
  { slug: 'hondajet',           name: 'HondaJet',           country: 'Japan',  founded_year: 2006 },
  { slug: 'jabiru',             name: 'Jabiru',             country: 'Australia', founded_year: 1988, homepage_url: 'https://jabiru.net.au/' },
  { slug: 'lancair',            name: 'Lancair',            country: 'USA',    founded_year: 1981 },
  { slug: 'maule',              name: 'Maule',              country: 'USA',    founded_year: 1941 },
  { slug: 'mooney',             name: 'Mooney',             country: 'USA',    founded_year: 1929 },
  { slug: 'pilatus',            name: 'Pilatus',            country: 'Switzerland', founded_year: 1939, homepage_url: 'https://www.pilatus-aircraft.com/' },
  { slug: 'piper',              name: 'Piper',              country: 'USA',    founded_year: 1937, homepage_url: 'https://www.piper.com/' },
  { slug: 'pipistrel',          name: 'Pipistrel',          country: 'Slovenia', founded_year: 1989, homepage_url: 'https://www.pipistrel-aircraft.com/' },
  { slug: 'pitts',              name: 'Pitts (Aviat)',      country: 'USA',    founded_year: 1944 },
  { slug: 'robinson',           name: 'Robinson Helicopter', country: 'USA',   founded_year: 1973, homepage_url: 'https://robinsonheli.com/' },
  { slug: 'schweizer',          name: 'Schweizer',          country: 'USA',    founded_year: 1939 },
  { slug: 'sling',              name: 'Sling Aircraft',     country: 'South Africa', founded_year: 2006, homepage_url: 'https://airplanefactory.com/' },
  { slug: 'socata',             name: 'Socata',             country: 'France', founded_year: 1911 },
  { slug: 'tecnam',             name: 'Tecnam',             country: 'Italy',  founded_year: 1986, homepage_url: 'https://www.tecnam.com/' },
  { slug: 'vans',               name: 'Vans Aircraft',      country: 'USA',    founded_year: 1973, homepage_url: 'https://www.vansaircraft.com/' },
  { slug: 'autogyro',           name: 'AutoGyro',           country: 'Germany', founded_year: 1999 },
  { slug: 'magni',              name: 'Magni Gyro',         country: 'Italy',  founded_year: 1990 },
  { slug: 'rotorway',           name: 'Rotorway',           country: 'USA',    founded_year: 1961 },
  { slug: 'schempp-hirth',      name: 'Schempp-Hirth',      country: 'Germany', founded_year: 1935 },
  { slug: 'schleicher',         name: 'Alexander Schleicher', country: 'Germany', founded_year: 1927 },
  { slug: 'icon',               name: 'Icon Aircraft',      country: 'USA',    founded_year: 2006 },
  { slug: 'flight-design',      name: 'Flight Design',      country: 'Germany', founded_year: 1988 },
  { slug: 'american-champion',  name: 'American Champion',  country: 'USA',    founded_year: 1989 },
];

// Build a model row. All optional fields default to null so callers can
// trust the shape; mission defaults to an empty array.
const m = (row) => ({
  variant: null, type_designator: null, mission: [],
  year_first: null, year_last: null,
  mtow_kg: null, seats: null, engine_type: null, engine_count: 1,
  cruise_kts: null, range_nm: null, fuel_burn_lph: null, ceiling_ft: null,
  wikipedia_url: null, hero_image_url: null, description: null,
  source: 'seed', aliases: [],
  ...row,
  full_name: row.full_name ?? `${makeName(row.make)} ${row.family}${row.variant ? ' ' + row.variant : ''}`,
  slug: row.slug ?? `${row.make}-${(row.family + (row.variant ? '-' + row.variant : '')).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')}`,
});

function makeName(slug) {
  const found = MAKES_SEED.find((mk) => mk.slug === slug);
  return found ? found.name : slug;
}

export const MODELS_SEED = [
  // ── CESSNA — single-engine piston ─────────────────────────────────
  m({ make: 'cessna', family: '150',    type_designator: 'C150', category: 'Single Engine Piston', mission: ['trainer'], year_first: 1958, year_last: 1977, mtow_kg: 726,  seats: 2, engine_type: 'Continental O-200',     cruise_kts: 90,  range_nm: 350, fuel_burn_lph: 22, ceiling_ft: 14700, aliases: ['C150', 'Cessna 150'] }),
  m({ make: 'cessna', family: '152',    type_designator: 'C152', category: 'Single Engine Piston', mission: ['trainer'], year_first: 1977, year_last: 1985, mtow_kg: 757,  seats: 2, engine_type: 'Lycoming O-235',       cruise_kts: 95,  range_nm: 350, fuel_burn_lph: 23, ceiling_ft: 14700, aliases: ['C152', 'Cessna 152'] }),
  m({ make: 'cessna', family: '172',    variant: 'M Skyhawk', type_designator: 'C172', category: 'Single Engine Piston', mission: ['trainer','tourer'], year_first: 1973, year_last: 1976, mtow_kg: 1043, seats: 4, engine_type: 'Lycoming O-320', cruise_kts: 115, range_nm: 480, fuel_burn_lph: 32, ceiling_ft: 13000, aliases: ['C172M','172M'] }),
  m({ make: 'cessna', family: '172',    variant: 'N Skyhawk', type_designator: 'C172', category: 'Single Engine Piston', mission: ['trainer','tourer'], year_first: 1977, year_last: 1980, mtow_kg: 1043, seats: 4, engine_type: 'Lycoming O-320', cruise_kts: 115, range_nm: 460, fuel_burn_lph: 32, ceiling_ft: 13000, aliases: ['C172N','172N'] }),
  m({ make: 'cessna', family: '172',    variant: 'P Skyhawk', type_designator: 'C172', category: 'Single Engine Piston', mission: ['trainer','tourer'], year_first: 1981, year_last: 1986, mtow_kg: 1089, seats: 4, engine_type: 'Lycoming O-320', cruise_kts: 116, range_nm: 530, fuel_burn_lph: 32, ceiling_ft: 13000, aliases: ['C172P','172P'] }),
  m({ make: 'cessna', family: '172',    variant: 'R Skyhawk', type_designator: 'C172', category: 'Single Engine Piston', mission: ['trainer','tourer'], year_first: 1996, year_last: 2007, mtow_kg: 1111, seats: 4, engine_type: 'Lycoming IO-360-L2A', cruise_kts: 122, range_nm: 580, fuel_burn_lph: 32, ceiling_ft: 13500, aliases: ['C172R','172R'] }),
  m({ make: 'cessna', family: '172',    variant: 'S Skyhawk', type_designator: 'C172', category: 'Single Engine Piston', mission: ['trainer','tourer'], year_first: 1998,                  mtow_kg: 1157, seats: 4, engine_type: 'Lycoming IO-360-L2A', cruise_kts: 124, range_nm: 640, fuel_burn_lph: 32, ceiling_ft: 14000, aliases: ['C172S','172S','Skyhawk SP','Skyhawk'] }),
  m({ make: 'cessna', family: '177',    variant: 'Cardinal',    type_designator: 'C177', category: 'Single Engine Piston', mission: ['tourer'], year_first: 1968, year_last: 1978, mtow_kg: 1134, seats: 4, engine_type: 'Lycoming O-360', cruise_kts: 132, range_nm: 600, fuel_burn_lph: 38, ceiling_ft: 14600, aliases: ['Cardinal','C177'] }),
  m({ make: 'cessna', family: '177',    variant: 'RG Cardinal', type_designator: 'C77R', category: 'Single Engine Piston', mission: ['tourer'], year_first: 1971, year_last: 1978, mtow_kg: 1270, seats: 4, engine_type: 'Lycoming IO-360', cruise_kts: 148, range_nm: 720, fuel_burn_lph: 42, ceiling_ft: 17100, aliases: ['Cardinal RG','C177RG'] }),
  m({ make: 'cessna', family: '180',    variant: 'Skywagon', type_designator: 'C180', category: 'Single Engine Piston', mission: ['tourer','floats','working'], year_first: 1953, year_last: 1981, mtow_kg: 1270, seats: 6, engine_type: 'Continental O-470', cruise_kts: 142, range_nm: 800, fuel_burn_lph: 47, ceiling_ft: 17700, aliases: ['C180','Skywagon 180'] }),
  m({ make: 'cessna', family: '182',    variant: 'P Skylane', type_designator: 'C182', category: 'Single Engine Piston', mission: ['tourer'], year_first: 1972, year_last: 1976, mtow_kg: 1338, seats: 4, engine_type: 'Continental O-470', cruise_kts: 138, range_nm: 720, fuel_burn_lph: 50, ceiling_ft: 14900, aliases: ['C182P','182P'] }),
  m({ make: 'cessna', family: '182',    variant: 'Q Skylane', type_designator: 'C182', category: 'Single Engine Piston', mission: ['tourer'], year_first: 1977, year_last: 1981, mtow_kg: 1338, seats: 4, engine_type: 'Continental O-470', cruise_kts: 140, range_nm: 750, fuel_burn_lph: 50, ceiling_ft: 14900, aliases: ['C182Q','182Q'] }),
  m({ make: 'cessna', family: '182',    variant: 'R Skylane', type_designator: 'C182', category: 'Single Engine Piston', mission: ['tourer'], year_first: 1981, year_last: 1986, mtow_kg: 1338, seats: 4, engine_type: 'Continental O-470', cruise_kts: 140, range_nm: 800, fuel_burn_lph: 50, ceiling_ft: 14900, aliases: ['C182R','182R'] }),
  m({ make: 'cessna', family: '182',    variant: 'T Skylane', type_designator: 'C182', category: 'Single Engine Piston', mission: ['tourer'], year_first: 2001,                  mtow_kg: 1406, seats: 4, engine_type: 'Lycoming IO-540-AB1A5', cruise_kts: 145, range_nm: 820, fuel_burn_lph: 52, ceiling_ft: 18100, aliases: ['C182T','182T','Skylane','Cessna Skylane'] }),
  m({ make: 'cessna', family: '185',    variant: 'Skywagon', type_designator: 'C185', category: 'Single Engine Piston', mission: ['floats','working','tourer'], year_first: 1961, year_last: 1985, mtow_kg: 1520, seats: 6, engine_type: 'Continental IO-520', cruise_kts: 145, range_nm: 700, fuel_burn_lph: 60, ceiling_ft: 17150, aliases: ['C185','Skywagon 185'] }),
  m({ make: 'cessna', family: '206',    variant: 'H Stationair', type_designator: 'C206', category: 'Single Engine Piston', mission: ['tourer','working','floats'], year_first: 1998,                  mtow_kg: 1633, seats: 6, engine_type: 'Lycoming IO-540-AC1A5', cruise_kts: 142, range_nm: 700, fuel_burn_lph: 65, ceiling_ft: 14800, aliases: ['C206','206H','Stationair'] }),
  m({ make: 'cessna', family: '206',    variant: 'T206H Turbo Stationair', type_designator: 'C206', category: 'Single Engine Piston', mission: ['tourer','working'], year_first: 1998,                  mtow_kg: 1633, seats: 6, engine_type: 'Lycoming TIO-540-AJ1A', cruise_kts: 164, range_nm: 700, fuel_burn_lph: 75, ceiling_ft: 27000, aliases: ['T206H','Turbo Stationair'] }),
  m({ make: 'cessna', family: '210',    variant: 'L Centurion', type_designator: 'C210', category: 'Single Engine Piston', mission: ['tourer'], year_first: 1972, year_last: 1976, mtow_kg: 1723, seats: 6, engine_type: 'Continental IO-520', cruise_kts: 165, range_nm: 900, fuel_burn_lph: 65, ceiling_ft: 17200, aliases: ['C210L','210L'] }),
  m({ make: 'cessna', family: '210',    variant: 'N Centurion', type_designator: 'C210', category: 'Single Engine Piston', mission: ['tourer'], year_first: 1979, year_last: 1984, mtow_kg: 1723, seats: 6, engine_type: 'Continental IO-520', cruise_kts: 168, range_nm: 900, fuel_burn_lph: 65, ceiling_ft: 17200, aliases: ['C210N','210N','Centurion'] }),

  // ── CESSNA — twin piston ────────────────────────────────────────
  m({ make: 'cessna', family: '310',    type_designator: 'C310', category: 'Multi Engine Piston', mission: ['tourer'], engine_count: 2, year_first: 1954, year_last: 1980, mtow_kg: 2495, seats: 6, engine_type: '2x Continental IO-520', cruise_kts: 195, range_nm: 940, fuel_burn_lph: 110, ceiling_ft: 19750, aliases: ['C310'] }),
  m({ make: 'cessna', family: '337',    variant: 'Skymaster', type_designator: 'C337', category: 'Multi Engine Piston', mission: ['tourer'], engine_count: 2, year_first: 1965, year_last: 1980, mtow_kg: 2100, seats: 6, engine_type: '2x Continental IO-360', cruise_kts: 175, range_nm: 870, fuel_burn_lph: 90, ceiling_ft: 19500, aliases: ['C337','Skymaster','Push-pull'] }),

  // ── CESSNA — turboprop ──────────────────────────────────────────
  m({ make: 'cessna', family: '208',    variant: 'B Grand Caravan', type_designator: 'C208', category: 'Turboprop', mission: ['working','floats'], year_first: 1990,                  mtow_kg: 4109, seats: 14, engine_type: 'PT6A-114A', cruise_kts: 186, range_nm: 964, fuel_burn_lph: 200, ceiling_ft: 25000, aliases: ['C208B','Grand Caravan','Caravan'] }),
  m({ make: 'cessna', family: '208',    variant: 'Caravan', type_designator: 'C208', category: 'Turboprop', mission: ['working','floats'], year_first: 1984,                  mtow_kg: 3629, seats: 9, engine_type: 'PT6A-114', cruise_kts: 186, range_nm: 1070, fuel_burn_lph: 180, ceiling_ft: 25000, aliases: ['C208','Caravan I'] }),

  // ── CESSNA — Citation jets ──────────────────────────────────────
  m({ make: 'cessna', family: 'Citation', variant: 'Mustang', type_designator: 'C510', category: 'Light Jet', engine_count: 2, year_first: 2006, year_last: 2017, mtow_kg: 3921, seats: 5, engine_type: '2x PW615F', cruise_kts: 340, range_nm: 1150, ceiling_ft: 41000, aliases: ['Citation Mustang','C510'] }),
  m({ make: 'cessna', family: 'Citation', variant: 'M2',       type_designator: 'C25M', category: 'Light Jet', engine_count: 2, year_first: 2013,                  mtow_kg: 4853, seats: 7, engine_type: '2x FJ44-1AP-21', cruise_kts: 404, range_nm: 1550, ceiling_ft: 41000, aliases: ['Citation M2','C25M'] }),
  m({ make: 'cessna', family: 'Citation', variant: 'CJ3+',     type_designator: 'C25B', category: 'Light Jet', engine_count: 2, year_first: 2014,                  mtow_kg: 6291, seats: 8, engine_type: '2x FJ44-3A', cruise_kts: 416, range_nm: 1875, ceiling_ft: 45000, aliases: ['CJ3+','Citation CJ3+'] }),
  m({ make: 'cessna', family: 'Citation', variant: 'CJ4',      type_designator: 'C25C', category: 'Midsize Jet', engine_count: 2, year_first: 2010,                  mtow_kg: 7761, seats: 9, engine_type: '2x FJ44-4A', cruise_kts: 451, range_nm: 2165, ceiling_ft: 45000, aliases: ['CJ4','Citation CJ4'] }),
  m({ make: 'cessna', family: 'Citation', variant: 'XLS+',     type_designator: 'C56X', category: 'Midsize Jet', engine_count: 2, year_first: 2008,                  mtow_kg: 9163, seats: 9, engine_type: '2x PW545B', cruise_kts: 441, range_nm: 1858, ceiling_ft: 45000, aliases: ['XLS+','Citation XLS+'] }),
  m({ make: 'cessna', family: 'Citation', variant: 'Latitude', type_designator: 'C68A', category: 'Midsize Jet', engine_count: 2, year_first: 2015,                  mtow_kg: 13608, seats: 9, engine_type: '2x PW306D1', cruise_kts: 446, range_nm: 2700, ceiling_ft: 45000, aliases: ['Citation Latitude'] }),
  m({ make: 'cessna', family: 'Citation', variant: 'Longitude', type_designator: 'C700', category: 'Heavy Jet', engine_count: 2, year_first: 2019,                  mtow_kg: 17917, seats: 12, engine_type: '2x Honeywell HTF7700L', cruise_kts: 483, range_nm: 3500, ceiling_ft: 45000, aliases: ['Citation Longitude'] }),

  // ── PIPER — single piston ──────────────────────────────────────
  m({ make: 'piper', family: 'PA-18',    variant: 'Super Cub', type_designator: 'PA18', category: 'Single Engine Piston', mission: ['floats','working','tourer'], year_first: 1949, year_last: 1994, mtow_kg: 794, seats: 2, engine_type: 'Lycoming O-320', cruise_kts: 100, range_nm: 460, fuel_burn_lph: 22, ceiling_ft: 19000, aliases: ['PA-18','Super Cub','PA18'] }),
  m({ make: 'piper', family: 'PA-22',    variant: 'Tri-Pacer', type_designator: 'PA22', category: 'Single Engine Piston', mission: ['tourer'], year_first: 1951, year_last: 1964, mtow_kg: 907, seats: 4, engine_type: 'Lycoming O-320', cruise_kts: 120, range_nm: 460, fuel_burn_lph: 32, ceiling_ft: 16500, aliases: ['Tri-Pacer','PA22'] }),
  m({ make: 'piper', family: 'PA-28',    variant: '140 Cherokee', type_designator: 'P28A', category: 'Single Engine Piston', mission: ['trainer','tourer'], year_first: 1964, year_last: 1977, mtow_kg: 975, seats: 4, engine_type: 'Lycoming O-320', cruise_kts: 108, range_nm: 480, fuel_burn_lph: 30, ceiling_ft: 14300, aliases: ['Cherokee 140','PA-28-140'] }),
  m({ make: 'piper', family: 'PA-28',    variant: '161 Warrior', type_designator: 'P28A', category: 'Single Engine Piston', mission: ['trainer','tourer'], year_first: 1976,                  mtow_kg: 1055, seats: 4, engine_type: 'Lycoming O-320-D3G', cruise_kts: 117, range_nm: 530, fuel_burn_lph: 32, ceiling_ft: 14000, aliases: ['Warrior','PA-28-161','Warrior III','Warrior II'] }),
  m({ make: 'piper', family: 'PA-28',    variant: '181 Archer', type_designator: 'P28A', category: 'Single Engine Piston', mission: ['trainer','tourer'], year_first: 1976,                  mtow_kg: 1157, seats: 4, engine_type: 'Lycoming O-360-A4M', cruise_kts: 128, range_nm: 522, fuel_burn_lph: 38, ceiling_ft: 14150, aliases: ['Archer','PA-28-181','Archer II','Archer III','Archer LX','Archer DX'] }),
  m({ make: 'piper', family: 'PA-28',    variant: '236 Dakota', type_designator: 'P28A', category: 'Single Engine Piston', mission: ['tourer'], year_first: 1979, year_last: 1995, mtow_kg: 1361, seats: 4, engine_type: 'Lycoming O-540-J3A5D', cruise_kts: 144, range_nm: 760, fuel_burn_lph: 50, ceiling_ft: 17500, aliases: ['Dakota','PA-28-236'] }),
  m({ make: 'piper', family: 'PA-28R',   variant: '200 Arrow II', type_designator: 'P28R', category: 'Single Engine Piston', mission: ['tourer'], year_first: 1972, year_last: 1976, mtow_kg: 1247, seats: 4, engine_type: 'Lycoming IO-360', cruise_kts: 137, range_nm: 700, fuel_burn_lph: 38, ceiling_ft: 16000, aliases: ['Arrow II','PA-28R-200'] }),
  m({ make: 'piper', family: 'PA-28R',   variant: '201 Arrow', type_designator: 'P28R', category: 'Single Engine Piston', mission: ['tourer'], year_first: 1977,                  mtow_kg: 1247, seats: 4, engine_type: 'Lycoming IO-360-C1C6', cruise_kts: 137, range_nm: 720, fuel_burn_lph: 40, ceiling_ft: 16200, aliases: ['Arrow','PA-28R-201','Arrow III','Arrow IV'] }),
  m({ make: 'piper', family: 'PA-32',    variant: '300 Cherokee Six', type_designator: 'PA32', category: 'Single Engine Piston', mission: ['tourer','working'], year_first: 1965, year_last: 1979, mtow_kg: 1633, seats: 7, engine_type: 'Lycoming IO-540', cruise_kts: 147, range_nm: 750, fuel_burn_lph: 60, ceiling_ft: 16250, aliases: ['Cherokee Six','PA-32-300'] }),
  m({ make: 'piper', family: 'PA-32R',   variant: '301 Saratoga', type_designator: 'P32R', category: 'Single Engine Piston', mission: ['tourer'], year_first: 1980, year_last: 2009, mtow_kg: 1633, seats: 6, engine_type: 'Lycoming IO-540-K1G5', cruise_kts: 165, range_nm: 800, fuel_burn_lph: 60, ceiling_ft: 16700, aliases: ['Saratoga','PA-32R-301','Saratoga II HP','Saratoga TC'] }),
  m({ make: 'piper', family: 'PA-46',    variant: '350 Malibu Mirage', type_designator: 'PA46', category: 'Single Engine Piston', mission: ['tourer'], year_first: 1989, year_last: 2014, mtow_kg: 1969, seats: 6, engine_type: 'Lycoming TIO-540-AE2A', cruise_kts: 213, range_nm: 1345, fuel_burn_lph: 80, ceiling_ft: 25000, aliases: ['Malibu','Mirage','PA-46-350P'] }),
  m({ make: 'piper', family: 'PA-46',    variant: 'M350', type_designator: 'PA46', category: 'Single Engine Piston', mission: ['tourer'], year_first: 2015,                  mtow_kg: 1969, seats: 6, engine_type: 'Lycoming TIO-540-AE2A', cruise_kts: 213, range_nm: 1343, fuel_burn_lph: 80, ceiling_ft: 25000, aliases: ['M350','Piper M350'] }),

  // ── PIPER — twin piston ────────────────────────────────────────
  m({ make: 'piper', family: 'PA-23',    variant: '250 Aztec', type_designator: 'PA23', category: 'Multi Engine Piston', mission: ['tourer'], engine_count: 2, year_first: 1959, year_last: 1981, mtow_kg: 2358, seats: 6, engine_type: '2x Lycoming IO-540', cruise_kts: 175, range_nm: 1000, fuel_burn_lph: 110, ceiling_ft: 17600, aliases: ['Aztec','PA-23-250'] }),
  m({ make: 'piper', family: 'PA-30',    variant: 'Twin Comanche', type_designator: 'PA30', category: 'Multi Engine Piston', mission: ['tourer'], engine_count: 2, year_first: 1963, year_last: 1972, mtow_kg: 1633, seats: 4, engine_type: '2x Lycoming IO-320', cruise_kts: 173, range_nm: 1200, fuel_burn_lph: 75, ceiling_ft: 20000, aliases: ['Twin Comanche','PA-30'] }),
  m({ make: 'piper', family: 'PA-34',    variant: '200T Seneca II', type_designator: 'PA34', category: 'Multi Engine Piston', mission: ['tourer','trainer'], engine_count: 2, year_first: 1975, year_last: 1980, mtow_kg: 2073, seats: 6, engine_type: '2x Continental TSIO-360', cruise_kts: 188, range_nm: 1000, fuel_burn_lph: 95, ceiling_ft: 25000, aliases: ['Seneca II','PA-34-200T'] }),
  m({ make: 'piper', family: 'PA-34',    variant: '220T Seneca V', type_designator: 'PA34', category: 'Multi Engine Piston', mission: ['tourer','trainer'], engine_count: 2, year_first: 1997,                  mtow_kg: 2155, seats: 6, engine_type: '2x Continental TSIO-360-RB', cruise_kts: 200, range_nm: 800, fuel_burn_lph: 105, ceiling_ft: 25000, aliases: ['Seneca V','PA-34-220T'] }),
  m({ make: 'piper', family: 'PA-44',    variant: 'Seminole', type_designator: 'PA44', category: 'Multi Engine Piston', mission: ['trainer'], engine_count: 2, year_first: 1979,                  mtow_kg: 1723, seats: 4, engine_type: '2x Lycoming O-360', cruise_kts: 162, range_nm: 700, fuel_burn_lph: 75, ceiling_ft: 17100, aliases: ['Seminole','PA-44-180'] }),

  // ── PIPER — turboprop ──────────────────────────────────────────
  m({ make: 'piper', family: 'PA-46',    variant: 'M500', type_designator: 'PAY1', category: 'Turboprop', mission: ['tourer'], year_first: 2015,                  mtow_kg: 2310, seats: 6, engine_type: 'PT6A-42A', cruise_kts: 260, range_nm: 1000, fuel_burn_lph: 175, ceiling_ft: 30000, aliases: ['M500','Piper M500','Meridian'] }),
  m({ make: 'piper', family: 'PA-46',    variant: 'M600', type_designator: 'PAY1', category: 'Turboprop', mission: ['tourer'], year_first: 2016,                  mtow_kg: 2722, seats: 6, engine_type: 'PT6A-42A', cruise_kts: 274, range_nm: 1658, fuel_burn_lph: 175, ceiling_ft: 30000, aliases: ['M600','Piper M600','M600 SLS'] }),

  // ── CIRRUS ────────────────────────────────────────────────────
  m({ make: 'cirrus', family: 'SR20', type_designator: 'SR20', category: 'Single Engine Piston', mission: ['trainer','tourer'], year_first: 1999,                  mtow_kg: 1383, seats: 5, engine_type: 'Lycoming IO-390-C3B6', cruise_kts: 155, range_nm: 770, fuel_burn_lph: 38, ceiling_ft: 17500, aliases: ['SR20'] }),
  m({ make: 'cirrus', family: 'SR22', type_designator: 'SR22', category: 'Single Engine Piston', mission: ['tourer'], year_first: 2001,                  mtow_kg: 1542, seats: 5, engine_type: 'Continental IO-550-N', cruise_kts: 183, range_nm: 1170, fuel_burn_lph: 65, ceiling_ft: 17500, aliases: ['SR22'] }),
  m({ make: 'cirrus', family: 'SR22', variant: 'T', type_designator: 'SR22', category: 'Single Engine Piston', mission: ['tourer'], year_first: 2006,                  mtow_kg: 1633, seats: 5, engine_type: 'Continental TSIO-550-K', cruise_kts: 213, range_nm: 1207, fuel_burn_lph: 70, ceiling_ft: 25000, aliases: ['SR22T','SR22 T','SR22 Turbo','SR22T GTS'] }),
  m({ make: 'cirrus', family: 'Vision Jet', variant: 'SF50', type_designator: 'SF50', category: 'Light Jet', mission: ['tourer'], year_first: 2016,                  mtow_kg: 2722, seats: 7, engine_type: 'Williams FJ33-5A', cruise_kts: 311, range_nm: 1275, ceiling_ft: 31000, aliases: ['SF50','Vision Jet','Cirrus Vision'] }),

  // ── BEECHCRAFT ────────────────────────────────────────────────
  m({ make: 'beechcraft', family: 'Bonanza', variant: 'V35B',    type_designator: 'BE35', category: 'Single Engine Piston', mission: ['tourer'], year_first: 1947, year_last: 1982, mtow_kg: 1542, seats: 4, engine_type: 'Continental IO-520-BA', cruise_kts: 174, range_nm: 880, fuel_burn_lph: 60, ceiling_ft: 17800, aliases: ['V35','V-tail','V35B','Bonanza V35B'] }),
  m({ make: 'beechcraft', family: 'Bonanza', variant: 'F33A',   type_designator: 'BE33', category: 'Single Engine Piston', mission: ['tourer'], year_first: 1970, year_last: 1995, mtow_kg: 1542, seats: 4, engine_type: 'Continental IO-520', cruise_kts: 165, range_nm: 720, fuel_burn_lph: 60, ceiling_ft: 17500, aliases: ['F33A','Bonanza F33A'] }),
  m({ make: 'beechcraft', family: 'Bonanza', variant: 'A36',    type_designator: 'BE36', category: 'Single Engine Piston', mission: ['tourer'], year_first: 1968,                  mtow_kg: 1655, seats: 6, engine_type: 'Continental IO-550-B', cruise_kts: 172, range_nm: 920, fuel_burn_lph: 60, ceiling_ft: 18500, aliases: ['A36','Bonanza A36','G36'] }),
  m({ make: 'beechcraft', family: 'Bonanza', variant: 'G36',    type_designator: 'BE36', category: 'Single Engine Piston', mission: ['tourer'], year_first: 2006,                  mtow_kg: 1655, seats: 6, engine_type: 'Continental IO-550-B', cruise_kts: 174, range_nm: 920, fuel_burn_lph: 65, ceiling_ft: 18500, aliases: ['G36','Bonanza G36'] }),
  m({ make: 'beechcraft', family: 'Baron', variant: '55',      type_designator: 'BE55', category: 'Multi Engine Piston', mission: ['tourer'], engine_count: 2, year_first: 1961, year_last: 1982, mtow_kg: 2313, seats: 6, engine_type: '2x Continental IO-470/520', cruise_kts: 200, range_nm: 1000, fuel_burn_lph: 100, ceiling_ft: 19200, aliases: ['Baron 55','BE55','55 Baron'] }),
  m({ make: 'beechcraft', family: 'Baron', variant: '58',      type_designator: 'BE58', category: 'Multi Engine Piston', mission: ['tourer'], engine_count: 2, year_first: 1970,                  mtow_kg: 2495, seats: 6, engine_type: '2x Continental IO-550-C', cruise_kts: 200, range_nm: 1480, fuel_burn_lph: 108, ceiling_ft: 20688, aliases: ['Baron 58','BE58','58 Baron','G58'] }),
  m({ make: 'beechcraft', family: 'King Air', variant: 'C90GTx', type_designator: 'BE9L', category: 'Turboprop', engine_count: 2, year_first: 2010,                  mtow_kg: 4581, seats: 8, engine_type: '2x PT6A-135A', cruise_kts: 270, range_nm: 1260, ceiling_ft: 30000, aliases: ['C90GTx','King Air C90'] }),
  m({ make: 'beechcraft', family: 'King Air', variant: '250', type_designator: 'BE20', category: 'Turboprop', engine_count: 2, year_first: 2009,                  mtow_kg: 5670, seats: 9, engine_type: '2x PT6A-52', cruise_kts: 310, range_nm: 1720, ceiling_ft: 35000, aliases: ['King Air 250','B200GT','250 King Air'] }),
  m({ make: 'beechcraft', family: 'King Air', variant: '350i', type_designator: 'BE30', category: 'Turboprop', engine_count: 2, year_first: 1990,                  mtow_kg: 6804, seats: 11, engine_type: '2x PT6A-60A', cruise_kts: 312, range_nm: 1806, ceiling_ft: 35000, aliases: ['King Air 350','350i','King Air 350i'] }),

  // ── DIAMOND ────────────────────────────────────────────────────
  m({ make: 'diamond', family: 'DA20', variant: 'C1', type_designator: 'DV20', category: 'Single Engine Piston', mission: ['trainer'], year_first: 1995,                  mtow_kg: 800, seats: 2, engine_type: 'Continental IO-240-B', cruise_kts: 138, range_nm: 540, fuel_burn_lph: 22, ceiling_ft: 13100, aliases: ['DA20','Katana','Eclipse','Evolution','DA20-C1'] }),
  m({ make: 'diamond', family: 'DA40', variant: 'NG', type_designator: 'DA40', category: 'Single Engine Piston', mission: ['trainer','tourer'], year_first: 2010,                  mtow_kg: 1280, seats: 4, engine_type: 'Austro AE300', cruise_kts: 154, range_nm: 940, fuel_burn_lph: 23, ceiling_ft: 16400, aliases: ['DA40 NG','DA40NG','Diamond Star NG'] }),
  m({ make: 'diamond', family: 'DA40', variant: 'XL', type_designator: 'DA40', category: 'Single Engine Piston', mission: ['trainer','tourer'], year_first: 2007,                  mtow_kg: 1200, seats: 4, engine_type: 'Lycoming IO-360-M1A', cruise_kts: 150, range_nm: 720, fuel_burn_lph: 35, ceiling_ft: 16400, aliases: ['DA40 XL','DA40-XL','Diamond Star'] }),
  m({ make: 'diamond', family: 'DA42', variant: 'VI Twin Star', type_designator: 'DA42', category: 'Multi Engine Piston', mission: ['trainer','tourer'], engine_count: 2, year_first: 2012,                  mtow_kg: 1999, seats: 4, engine_type: '2x Austro AE300', cruise_kts: 197, range_nm: 1100, fuel_burn_lph: 42, ceiling_ft: 18000, aliases: ['DA42','DA42-VI','Twin Star','DA42 NG'] }),
  m({ make: 'diamond', family: 'DA50', variant: 'RG', type_designator: 'DA50', category: 'Single Engine Piston', mission: ['tourer'], year_first: 2020,                  mtow_kg: 1999, seats: 5, engine_type: 'Continental CD-300', cruise_kts: 181, range_nm: 750, fuel_burn_lph: 45, ceiling_ft: 20000, aliases: ['DA50 RG','DA50RG'] }),
  m({ make: 'diamond', family: 'DA62', type_designator: 'DA62', category: 'Multi Engine Piston', mission: ['tourer'], engine_count: 2, year_first: 2015,                  mtow_kg: 2300, seats: 7, engine_type: '2x Austro AE330', cruise_kts: 192, range_nm: 1283, fuel_burn_lph: 50, ceiling_ft: 20000, aliases: ['DA62'] }),

  // ── MOONEY ────────────────────────────────────────────────────
  m({ make: 'mooney', family: 'M20', variant: 'J 201', type_designator: 'M20P', category: 'Single Engine Piston', mission: ['tourer'], year_first: 1977, year_last: 1998, mtow_kg: 1145, seats: 4, engine_type: 'Lycoming IO-360-A3B6D', cruise_kts: 150, range_nm: 1000, fuel_burn_lph: 38, ceiling_ft: 18800, aliases: ['Mooney 201','M20J'] }),
  m({ make: 'mooney', family: 'M20', variant: 'K 231 Turbo', type_designator: 'M20T', category: 'Single Engine Piston', mission: ['tourer'], year_first: 1979, year_last: 1985, mtow_kg: 1315, seats: 4, engine_type: 'Continental TSIO-360-GB1', cruise_kts: 175, range_nm: 1000, fuel_burn_lph: 50, ceiling_ft: 24000, aliases: ['Mooney 231','M20K'] }),
  m({ make: 'mooney', family: 'M20', variant: 'M Bravo', type_designator: 'M20T', category: 'Single Engine Piston', mission: ['tourer'], year_first: 1989, year_last: 2008, mtow_kg: 1542, seats: 4, engine_type: 'Lycoming TIO-540-AF1A', cruise_kts: 220, range_nm: 1100, fuel_burn_lph: 65, ceiling_ft: 25000, aliases: ['Mooney Bravo','M20M'] }),
  m({ make: 'mooney', family: 'M20', variant: 'R Ovation', type_designator: 'M20P', category: 'Single Engine Piston', mission: ['tourer'], year_first: 1994,                  mtow_kg: 1542, seats: 4, engine_type: 'Continental IO-550-G', cruise_kts: 197, range_nm: 1300, fuel_burn_lph: 60, ceiling_ft: 20000, aliases: ['Mooney Ovation','M20R'] }),
  m({ make: 'mooney', family: 'M20', variant: 'TN Acclaim', type_designator: 'M20T', category: 'Single Engine Piston', mission: ['tourer'], year_first: 2007,                  mtow_kg: 1542, seats: 4, engine_type: 'Continental TSIO-550-G', cruise_kts: 242, range_nm: 1445, fuel_burn_lph: 75, ceiling_ft: 25000, aliases: ['Acclaim','Acclaim Type S','Acclaim Ultra','M20TN'] }),

  // ── PILATUS / DAHER / EMBRAER / HONDAJET — turboprops & jets ──
  m({ make: 'pilatus', family: 'PC-12', variant: '47E (NGX)', type_designator: 'PC12', category: 'Turboprop', mission: ['tourer','working'], year_first: 2008,                  mtow_kg: 4740, seats: 9, engine_type: 'PT6E-67XP', cruise_kts: 290, range_nm: 1845, fuel_burn_lph: 280, ceiling_ft: 30000, aliases: ['PC-12','PC12','PC-12 NGX','PC-12/47E'] }),
  m({ make: 'pilatus', family: 'PC-24', type_designator: 'PC24', category: 'Light Jet', engine_count: 2, year_first: 2017,                  mtow_kg: 8300, seats: 10, engine_type: '2x Williams FJ44-4A', cruise_kts: 440, range_nm: 2000, ceiling_ft: 45000, aliases: ['PC-24','PC24'] }),
  m({ make: 'daher', family: 'TBM', variant: '850', type_designator: 'TBM8', category: 'Turboprop', mission: ['tourer'], year_first: 2006, year_last: 2013, mtow_kg: 3354, seats: 6, engine_type: 'PT6A-66D', cruise_kts: 320, range_nm: 1585, fuel_burn_lph: 220, ceiling_ft: 31000, aliases: ['TBM 850','TBM850','TBM-850'] }),
  m({ make: 'daher', family: 'TBM', variant: '900', type_designator: 'TBM9', category: 'Turboprop', mission: ['tourer'], year_first: 2014, year_last: 2017, mtow_kg: 3354, seats: 6, engine_type: 'PT6A-66D', cruise_kts: 330, range_nm: 1730, fuel_burn_lph: 215, ceiling_ft: 31000, aliases: ['TBM 900','TBM900'] }),
  m({ make: 'daher', family: 'TBM', variant: '930', type_designator: 'TBM9', category: 'Turboprop', mission: ['tourer'], year_first: 2016,                  mtow_kg: 3354, seats: 6, engine_type: 'PT6A-66D', cruise_kts: 330, range_nm: 1730, fuel_burn_lph: 215, ceiling_ft: 31000, aliases: ['TBM 930','TBM930'] }),
  m({ make: 'daher', family: 'TBM', variant: '960', type_designator: 'TBM9', category: 'Turboprop', mission: ['tourer'], year_first: 2022,                  mtow_kg: 3354, seats: 6, engine_type: 'PT6E-66XT', cruise_kts: 330, range_nm: 1730, fuel_burn_lph: 220, ceiling_ft: 31000, aliases: ['TBM 960','TBM960'] }),
  m({ make: 'embraer', family: 'Phenom', variant: '100', type_designator: 'E50P', category: 'Light Jet', engine_count: 2, year_first: 2008,                  mtow_kg: 4750, seats: 6, engine_type: '2x PW617F', cruise_kts: 390, range_nm: 1178, ceiling_ft: 41000, aliases: ['Phenom 100','EMB-500','E100'] }),
  m({ make: 'embraer', family: 'Phenom', variant: '300', type_designator: 'E55P', category: 'Light Jet', engine_count: 2, year_first: 2009,                  mtow_kg: 8150, seats: 9, engine_type: '2x PW535E', cruise_kts: 453, range_nm: 1971, ceiling_ft: 45000, aliases: ['Phenom 300','EMB-505','E300','Phenom 300E'] }),
  m({ make: 'hondajet', family: 'HA-420', type_designator: 'HDJT', category: 'Light Jet', engine_count: 2, year_first: 2015,                  mtow_kg: 4853, seats: 7, engine_type: '2x GE Honda HF120', cruise_kts: 422, range_nm: 1437, ceiling_ft: 43000, aliases: ['HondaJet','HA-420','HondaJet Elite'] }),

  // ── HELICOPTERS ────────────────────────────────────────────────
  m({ make: 'robinson', family: 'R22', variant: 'Beta II', type_designator: 'R22',  category: 'Helicopter', mission: ['trainer','working'], year_first: 1995,                  mtow_kg: 622, seats: 2, engine_type: 'Lycoming O-360', cruise_kts: 96, range_nm: 240, fuel_burn_lph: 38, ceiling_ft: 14000, aliases: ['R22','Robinson R22'] }),
  m({ make: 'robinson', family: 'R44', variant: 'Raven I', type_designator: 'R44',  category: 'Helicopter', mission: ['trainer','tourer','working'], year_first: 1992, year_last: 2002, mtow_kg: 1089, seats: 4, engine_type: 'Lycoming O-540', cruise_kts: 109, range_nm: 350, fuel_burn_lph: 56, ceiling_ft: 14000, aliases: ['R44','Robinson R44','Raven I'] }),
  m({ make: 'robinson', family: 'R44', variant: 'Raven II', type_designator: 'R44',  category: 'Helicopter', mission: ['trainer','tourer','working'], year_first: 2002,                  mtow_kg: 1134, seats: 4, engine_type: 'Lycoming IO-540-AE1A5', cruise_kts: 113, range_nm: 300, fuel_burn_lph: 64, ceiling_ft: 14000, aliases: ['R44 II','R44 Raven II','Raven 2'] }),
  m({ make: 'robinson', family: 'R66', type_designator: 'R66',  category: 'Helicopter', mission: ['tourer','working'], year_first: 2010,                  mtow_kg: 1225, seats: 5, engine_type: 'Rolls-Royce RR300', cruise_kts: 110, range_nm: 350, fuel_burn_lph: 95, ceiling_ft: 14000, aliases: ['R66','Robinson R66','R66 Turbine'] }),
  m({ make: 'bell', family: '206', variant: 'B-III JetRanger', type_designator: 'B06',  category: 'Helicopter', mission: ['tourer','working'], year_first: 1977, year_last: 2010, mtow_kg: 1451, seats: 5, engine_type: 'Rolls-Royce 250-C20', cruise_kts: 117, range_nm: 374, fuel_burn_lph: 110, ceiling_ft: 13500, aliases: ['Bell 206','206B','JetRanger','206 JetRanger'] }),
  m({ make: 'bell', family: '407', type_designator: 'B407', category: 'Helicopter', mission: ['tourer','working'], year_first: 1996,                  mtow_kg: 2268, seats: 7, engine_type: 'Rolls-Royce 250-C47B', cruise_kts: 133, range_nm: 330, fuel_burn_lph: 165, ceiling_ft: 18690, aliases: ['Bell 407','407 GXi','407GXi'] }),
  m({ make: 'bell', family: '412', type_designator: 'B412', category: 'Helicopter', mission: ['working'], engine_count: 2, year_first: 1981,                  mtow_kg: 5398, seats: 14, engine_type: '2x PT6T-3D', cruise_kts: 122, range_nm: 408, ceiling_ft: 20000, aliases: ['Bell 412','412EP','412EPI'] }),
  m({ make: 'airbus-helicopters', family: 'AS350', variant: 'B3 Squirrel', type_designator: 'AS50', category: 'Helicopter', mission: ['tourer','working'], year_first: 1997,                  mtow_kg: 2250, seats: 6, engine_type: 'Turbomeca Arriel 2B', cruise_kts: 133, range_nm: 357, fuel_burn_lph: 175, ceiling_ft: 13800, aliases: ['AS350','AS350 B3','Squirrel','H125','AS350B3'] }),
  m({ make: 'airbus-helicopters', family: 'EC130', variant: 'T2', type_designator: 'EC30', category: 'Helicopter', mission: ['tourer'], year_first: 2011,                  mtow_kg: 2500, seats: 8, engine_type: 'Turbomeca Arriel 2D', cruise_kts: 130, range_nm: 332, fuel_burn_lph: 175, ceiling_ft: 16000, aliases: ['EC130','EC130 T2','H130'] }),
  m({ make: 'schweizer', family: '300', variant: 'C', type_designator: 'S300', category: 'Helicopter', mission: ['trainer'], year_first: 1969,                  mtow_kg: 930, seats: 3, engine_type: 'Lycoming HIO-360', cruise_kts: 86, range_nm: 195, fuel_burn_lph: 40, ceiling_ft: 10200, aliases: ['Schweizer 300','S300','300C','Schweizer 300CB'] }),

  // ── LSA / ULTRALIGHT ──────────────────────────────────────────
  m({ make: 'tecnam', family: 'P92', variant: 'Echo', type_designator: 'P92', category: 'LSA', mission: ['trainer','tourer'], year_first: 1993,                  mtow_kg: 600, seats: 2, engine_type: 'Rotax 912', cruise_kts: 110, range_nm: 540, fuel_burn_lph: 16, ceiling_ft: 14000, aliases: ['P92','P92 Echo'] }),
  m({ make: 'tecnam', family: 'P2002', variant: 'Sierra', type_designator: 'P2', category: 'LSA', mission: ['trainer','tourer'], year_first: 2002,                  mtow_kg: 600, seats: 2, engine_type: 'Rotax 912 ULS', cruise_kts: 122, range_nm: 540, fuel_burn_lph: 17, ceiling_ft: 14000, aliases: ['P2002','Sierra'] }),
  m({ make: 'tecnam', family: 'P2008', type_designator: 'P28', category: 'LSA', mission: ['trainer','tourer'], year_first: 2009,                  mtow_kg: 600, seats: 2, engine_type: 'Rotax 912 ULS', cruise_kts: 118, range_nm: 600, fuel_burn_lph: 17, ceiling_ft: 14000, aliases: ['P2008','P2008JC'] }),
  m({ make: 'tecnam', family: 'P2010', variant: 'TDI', type_designator: 'P210', category: 'Single Engine Piston', mission: ['trainer','tourer'], year_first: 2017,                  mtow_kg: 1180, seats: 4, engine_type: 'Continental CD-170', cruise_kts: 138, range_nm: 800, fuel_burn_lph: 24, ceiling_ft: 14000, aliases: ['P2010 TDI','P2010'] }),
  m({ make: 'tecnam', family: 'P2012', variant: 'Traveller', type_designator: 'P12', category: 'Multi Engine Piston', mission: ['working'], engine_count: 2, year_first: 2018,                  mtow_kg: 3680, seats: 11, engine_type: '2x Lycoming TEO-540-C1A', cruise_kts: 194, range_nm: 950, fuel_burn_lph: 120, ceiling_ft: 22000, aliases: ['P2012','Traveller','P2012 Traveller'] }),
  m({ make: 'tecnam', family: 'P2006T', type_designator: 'P06T', category: 'Multi Engine Piston', mission: ['trainer','tourer'], engine_count: 2, year_first: 2009,                  mtow_kg: 1230, seats: 4, engine_type: '2x Rotax 912 S3', cruise_kts: 145, range_nm: 670, fuel_burn_lph: 35, ceiling_ft: 14000, aliases: ['P2006T'] }),
  m({ make: 'sling', family: '2', type_designator: 'SLNG', category: 'LSA', mission: ['trainer','tourer','kit'], year_first: 2009,                  mtow_kg: 600, seats: 2, engine_type: 'Rotax 912', cruise_kts: 120, range_nm: 800, fuel_burn_lph: 20, ceiling_ft: 14000, aliases: ['Sling 2'] }),
  m({ make: 'sling', family: 'TSi', type_designator: 'SLNG', category: 'Single Engine Piston', mission: ['tourer','kit'], year_first: 2018,                  mtow_kg: 1000, seats: 4, engine_type: 'Rotax 915iS', cruise_kts: 155, range_nm: 1050, fuel_burn_lph: 32, ceiling_ft: 18000, aliases: ['Sling TSi','TSi','Sling 4 TSi'] }),
  m({ make: 'sling', family: 'High Wing', type_designator: 'SLNG', category: 'LSA', mission: ['tourer','kit'], year_first: 2022,                  mtow_kg: 750, seats: 4, engine_type: 'Rotax 915iS', cruise_kts: 130, range_nm: 1000, fuel_burn_lph: 25, ceiling_ft: 14000, aliases: ['Sling High Wing','High Wing'] }),
  m({ make: 'pipistrel', family: 'Virus', variant: 'SW 121', type_designator: 'PVRS', category: 'LSA', mission: ['trainer','tourer'], year_first: 2016,                  mtow_kg: 600, seats: 2, engine_type: 'Rotax 912 S3', cruise_kts: 130, range_nm: 540, fuel_burn_lph: 14, ceiling_ft: 18000, aliases: ['Virus SW','Virus SW 121','Virus SW121'] }),
  m({ make: 'pipistrel', family: 'Velis', variant: 'Electro', type_designator: 'PVEL', category: 'LSA', mission: ['trainer'], year_first: 2020,                  mtow_kg: 600, seats: 2, engine_type: 'Pipistrel E-811 Electric', cruise_kts: 90, range_nm: 54, fuel_burn_lph: 0, ceiling_ft: 12000, aliases: ['Velis Electro','Velis'] }),
  m({ make: 'pipistrel', family: 'Panthera', type_designator: 'PNTR', category: 'Single Engine Piston', mission: ['tourer'], year_first: 2017,                  mtow_kg: 1315, seats: 4, engine_type: 'Lycoming IO-540', cruise_kts: 187, range_nm: 1000, fuel_burn_lph: 50, ceiling_ft: 25000, aliases: ['Panthera','Pipistrel Panthera'] }),
  m({ make: 'jabiru', family: 'J160', type_designator: 'JAB', category: 'LSA', mission: ['trainer'], year_first: 2003,                  mtow_kg: 540, seats: 2, engine_type: 'Jabiru 2200', cruise_kts: 105, range_nm: 380, fuel_burn_lph: 14, ceiling_ft: 10000, aliases: ['J160'] }),
  m({ make: 'jabiru', family: 'J170', type_designator: 'JAB', category: 'LSA', mission: ['trainer'], year_first: 2007,                  mtow_kg: 600, seats: 2, engine_type: 'Jabiru 2200', cruise_kts: 105, range_nm: 380, fuel_burn_lph: 14, ceiling_ft: 10000, aliases: ['J170'] }),
  m({ make: 'jabiru', family: 'J230', variant: 'D', type_designator: 'JAB', category: 'LSA', mission: ['tourer','trainer'], year_first: 2007,                  mtow_kg: 600, seats: 2, engine_type: 'Jabiru 3300A', cruise_kts: 118, range_nm: 700, fuel_burn_lph: 18, ceiling_ft: 13000, aliases: ['J230','J230-D','J230D'] }),
  m({ make: 'jabiru', family: 'J430', type_designator: 'JAB', category: 'Single Engine Piston', mission: ['tourer'], year_first: 2003,                  mtow_kg: 700, seats: 4, engine_type: 'Jabiru 3300A', cruise_kts: 120, range_nm: 700, fuel_burn_lph: 20, ceiling_ft: 13000, aliases: ['J430'] }),
  m({ make: 'foxbat', family: 'A22LS', variant: 'Foxbat', type_designator: 'A22', category: 'LSA', mission: ['trainer','tourer','floats'], year_first: 1996,                  mtow_kg: 600, seats: 2, engine_type: 'Rotax 912 ULS', cruise_kts: 95, range_nm: 540, fuel_burn_lph: 16, ceiling_ft: 14000, aliases: ['A22','A22LS','Foxbat A22','Aeroprakt A22'] }),
  m({ make: 'flight-design', family: 'CTLS', type_designator: 'CTLS', category: 'LSA', mission: ['trainer','tourer'], year_first: 2007,                  mtow_kg: 600, seats: 2, engine_type: 'Rotax 912 ULS', cruise_kts: 120, range_nm: 760, fuel_burn_lph: 17, ceiling_ft: 13500, aliases: ['CTLS','CT LS','Flight Design CTLS'] }),
  m({ make: 'bristell', family: 'NG5', variant: 'Speed Wing', type_designator: 'BRIS', category: 'LSA', mission: ['trainer','tourer'], year_first: 2011,                  mtow_kg: 600, seats: 2, engine_type: 'Rotax 912 ULS', cruise_kts: 130, range_nm: 760, fuel_burn_lph: 17, ceiling_ft: 14000, aliases: ['Bristell NG5','NG5'] }),
  m({ make: 'icon', family: 'A5', type_designator: 'ICN5', category: 'LSA', mission: ['floats','tourer'], year_first: 2014,                  mtow_kg: 686, seats: 2, engine_type: 'Rotax 912 iS', cruise_kts: 95, range_nm: 380, fuel_burn_lph: 17, ceiling_ft: 12500, aliases: ['Icon A5','A5'] }),

  // ── EXPERIMENTAL / KIT ────────────────────────────────────────
  m({ make: 'vans', family: 'RV-4', type_designator: 'RV4', category: 'Single Engine Piston', mission: ['kit','aerobatic','tourer'], year_first: 1979,                  mtow_kg: 680, seats: 2, engine_type: 'Lycoming O-320/360', cruise_kts: 165, range_nm: 600, fuel_burn_lph: 30, ceiling_ft: 17000, aliases: ['RV-4','RV4'] }),
  m({ make: 'vans', family: 'RV-6', type_designator: 'RV6', category: 'Single Engine Piston', mission: ['kit','tourer'], year_first: 1986,                  mtow_kg: 727, seats: 2, engine_type: 'Lycoming O-320/360', cruise_kts: 170, range_nm: 800, fuel_burn_lph: 32, ceiling_ft: 18000, aliases: ['RV-6','RV6','RV-6A'] }),
  m({ make: 'vans', family: 'RV-7', type_designator: 'RV7', category: 'Single Engine Piston', mission: ['kit','aerobatic','tourer'], year_first: 2001,                  mtow_kg: 816, seats: 2, engine_type: 'Lycoming O-360/IO-390', cruise_kts: 175, range_nm: 870, fuel_burn_lph: 32, ceiling_ft: 18000, aliases: ['RV-7','RV7','RV-7A'] }),
  m({ make: 'vans', family: 'RV-8', type_designator: 'RV8', category: 'Single Engine Piston', mission: ['kit','aerobatic'], year_first: 1996,                  mtow_kg: 816, seats: 2, engine_type: 'Lycoming O-360/IO-390', cruise_kts: 180, range_nm: 850, fuel_burn_lph: 32, ceiling_ft: 18000, aliases: ['RV-8','RV8','RV-8A'] }),
  m({ make: 'vans', family: 'RV-9', type_designator: 'RV9', category: 'Single Engine Piston', mission: ['kit','tourer'], year_first: 2000,                  mtow_kg: 816, seats: 2, engine_type: 'Lycoming O-235/320', cruise_kts: 165, range_nm: 800, fuel_burn_lph: 26, ceiling_ft: 17000, aliases: ['RV-9','RV9','RV-9A'] }),
  m({ make: 'vans', family: 'RV-10', type_designator: 'RV10', category: 'Single Engine Piston', mission: ['kit','tourer'], year_first: 2003,                  mtow_kg: 1225, seats: 4, engine_type: 'Lycoming IO-540', cruise_kts: 175, range_nm: 980, fuel_burn_lph: 50, ceiling_ft: 20000, aliases: ['RV-10','RV10'] }),
  m({ make: 'vans', family: 'RV-12', variant: 'iS', type_designator: 'RV12', category: 'LSA', mission: ['kit','trainer'], year_first: 2008,                  mtow_kg: 600, seats: 2, engine_type: 'Rotax 912 iS', cruise_kts: 119, range_nm: 530, fuel_burn_lph: 17, ceiling_ft: 13000, aliases: ['RV-12','RV-12iS','RV12'] }),
  m({ make: 'vans', family: 'RV-14', type_designator: 'RV14', category: 'Single Engine Piston', mission: ['kit','tourer','aerobatic'], year_first: 2012,                  mtow_kg: 884, seats: 2, engine_type: 'Lycoming IO-390', cruise_kts: 170, range_nm: 850, fuel_burn_lph: 38, ceiling_ft: 18000, aliases: ['RV-14','RV14','RV-14A'] }),
  m({ make: 'lancair', family: 'IV-P', type_designator: 'LNC4', category: 'Single Engine Piston', mission: ['kit','tourer'], year_first: 1991,                  mtow_kg: 1542, seats: 4, engine_type: 'Continental TSIO-550', cruise_kts: 280, range_nm: 1300, fuel_burn_lph: 80, ceiling_ft: 25000, aliases: ['Lancair IV','IV-P','Lancair IV-P'] }),

  // ── AEROBATIC ──────────────────────────────────────────────────
  m({ make: 'aviat', family: 'Husky', variant: 'A-1C', type_designator: 'HUSK', category: 'Single Engine Piston', mission: ['floats','working','tourer'], year_first: 1998,                  mtow_kg: 907, seats: 2, engine_type: 'Lycoming IO-360', cruise_kts: 124, range_nm: 600, fuel_burn_lph: 35, ceiling_ft: 20000, aliases: ['Husky','Aviat Husky','A-1C'] }),
  m({ make: 'pitts', family: 'S-2C', type_designator: 'PTS2', category: 'Single Engine Piston', mission: ['aerobatic'], year_first: 1971,                  mtow_kg: 762, seats: 2, engine_type: 'Lycoming AEIO-540', cruise_kts: 152, range_nm: 320, fuel_burn_lph: 60, ceiling_ft: 21000, aliases: ['Pitts S-2C','S-2C','Pitts Special'] }),
  m({ make: 'extra', family: '300', variant: 'L', type_designator: 'E300', category: 'Single Engine Piston', mission: ['aerobatic'], year_first: 1995,                  mtow_kg: 950, seats: 2, engine_type: 'Lycoming AEIO-540', cruise_kts: 200, range_nm: 540, fuel_burn_lph: 65, ceiling_ft: 16000, aliases: ['Extra 300','Extra 300L'] }),
  m({ make: 'american-champion', family: 'Decathlon', variant: '8KCAB Super', type_designator: 'BL8', category: 'Single Engine Piston', mission: ['aerobatic','tourer'], year_first: 1970,                  mtow_kg: 816, seats: 2, engine_type: 'Lycoming AEIO-360', cruise_kts: 122, range_nm: 540, fuel_burn_lph: 38, ceiling_ft: 16000, aliases: ['Decathlon','Super Decathlon','8KCAB'] }),

  // ── BUSH / FLOATS ──────────────────────────────────────────────
  m({ make: 'maule', family: 'M-7', variant: '235', type_designator: 'M7', category: 'Single Engine Piston', mission: ['floats','working','tourer'], year_first: 1984,                  mtow_kg: 1134, seats: 4, engine_type: 'Lycoming O-540', cruise_kts: 130, range_nm: 720, fuel_burn_lph: 50, ceiling_ft: 14500, aliases: ['Maule M-7','M-7-235'] }),
  m({ make: 'cubcrafters', family: 'Carbon Cub', variant: 'EX-3', type_designator: 'CUB', category: 'Single Engine Piston', mission: ['floats','working','kit'], year_first: 2017,                  mtow_kg: 855, seats: 2, engine_type: 'CC340 / Titan', cruise_kts: 105, range_nm: 530, fuel_burn_lph: 32, ceiling_ft: 18000, aliases: ['Carbon Cub','Carbon Cub EX-3','EX-3'] }),

  // ── AUSTRALIAN-MADE ────────────────────────────────────────────
  m({ make: 'gippsaero', family: 'GA8', variant: 'Airvan', type_designator: 'GA8', category: 'Single Engine Piston', mission: ['working','floats','tourer'], year_first: 2000,                  mtow_kg: 1814, seats: 8, engine_type: 'Lycoming IO-540', cruise_kts: 130, range_nm: 730, fuel_burn_lph: 60, ceiling_ft: 20000, aliases: ['GA8','Airvan','GippsAero Airvan','GA-8'] }),
  m({ make: 'gippsaero', family: 'GA10', variant: 'Airvan', type_designator: 'GA10', category: 'Turboprop', mission: ['working'], year_first: 2012,                  mtow_kg: 2268, seats: 9, engine_type: 'Rolls-Royce 250-B17F', cruise_kts: 153, range_nm: 800, fuel_burn_lph: 130, ceiling_ft: 25000, aliases: ['GA10','Airvan 10'] }),

  // ── GYROCOPTERS ────────────────────────────────────────────────
  m({ make: 'autogyro', family: 'Cavalon', type_designator: 'CVLN', category: 'Gyrocopter', mission: ['tourer'], year_first: 2011,                  mtow_kg: 560, seats: 2, engine_type: 'Rotax 914', cruise_kts: 95, range_nm: 425, fuel_burn_lph: 20, ceiling_ft: 12000, aliases: ['Cavalon','AutoGyro Cavalon'] }),
  m({ make: 'autogyro', family: 'Calidus', type_designator: 'CLDS', category: 'Gyrocopter', mission: ['tourer'], year_first: 2009,                  mtow_kg: 560, seats: 2, engine_type: 'Rotax 914', cruise_kts: 100, range_nm: 425, fuel_burn_lph: 20, ceiling_ft: 12000, aliases: ['Calidus','AutoGyro Calidus'] }),
  m({ make: 'magni', family: 'M16', type_designator: 'M16', category: 'Gyrocopter', mission: ['tourer'], year_first: 1998,                  mtow_kg: 540, seats: 2, engine_type: 'Rotax 914', cruise_kts: 90, range_nm: 250, fuel_burn_lph: 20, ceiling_ft: 12000, aliases: ['Magni M16','M16 Tandem'] }),
  m({ make: 'magni', family: 'M22', variant: 'Voyager', type_designator: 'M22', category: 'Gyrocopter', mission: ['tourer'], year_first: 2009,                  mtow_kg: 560, seats: 2, engine_type: 'Rotax 914', cruise_kts: 90, range_nm: 250, fuel_burn_lph: 20, ceiling_ft: 12000, aliases: ['Magni M22','Voyager','M22 Voyager'] }),

  // ── GLIDERS ────────────────────────────────────────────────────
  m({ make: 'schempp-hirth', family: 'Discus', variant: '2', type_designator: 'DSC2', category: 'Glider', mission: [], year_first: 1998,                  mtow_kg: 525, seats: 1, engine_type: null, aliases: ['Discus 2','Discus-2','Schempp-Hirth Discus 2'] }),
  m({ make: 'schleicher', family: 'ASW', variant: '28', type_designator: 'ASW28', category: 'Glider', mission: [], year_first: 1999,                  mtow_kg: 525, seats: 1, engine_type: null, aliases: ['ASW 28','ASW-28','ASW28','Schleicher ASW 28'] }),
  m({ make: 'schleicher', family: 'ASK', variant: '21', type_designator: 'ASK21', category: 'Glider', mission: ['trainer'], year_first: 1979,                  mtow_kg: 600, seats: 2, engine_type: null, aliases: ['ASK 21','ASK-21','ASK21','Schleicher ASK 21'] }),
];
